# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: Tests
  